name: liferay-3rd-party-demo-website-development
services:
  web:
    build:
      context: .
      target: development
    image: liferay-3rd-party-demo-website-development-web
    ports:
      - "3000:3000"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
    env_file:
      - .env.development
    container_name: development-web