import { env } from '../env'

export const PUBLIC_URL = env.PUBLIC_URL;
export const DOCUMENT_TITLE = env.REACT_APP_DOCUMENT_TITLE;
export const LIFERAY_AC_CHANNEL_ID = env.REACT_APP_LIFERAY_AC_CHANNEL_ID;
export const LIFERAY_AC_PROJECT_ID = env.REACT_APP_LIFERAY_AC_PROJECT_ID;
export const LIFERAY_AC_DATA_SOURCE_ID = env.REACT_APP_LIFERAY_AC_DATA_SOURCE_ID;
export const LIFERAY_AC_SCRIPT_URL = env.REACT_APP_LIFERAY_AC_SCRIPT_URL;
export const LIFERAY_AC_ENDPOINT = env.REACT_APP_LIFERAY_AC_ENDPOINT;
export const LIFERAY_HOST_BASE_URL = env.REACT_APP_LIFERAY_HOST_BASE_URL;
const LIFERAY_HEADLESS_ADMIN_USER_BASE_PATH = env.REACT_APP_LIFERAY_HEADLESS_ADMIN_USER_BASE_PATH;
export const LIFERAY_HEADLESS_ADMIN_USER_ENDPOINT = `${LIFERAY_HOST_BASE_URL}/${LIFERAY_HEADLESS_ADMIN_USER_BASE_PATH}`;
const LIFERAY_HEADLESS_DELIVERY_BASE_PATH = env.REACT_APP_LIFERAY_HEADLESS_DELIVERY_BASE_PATH;
export const LIFERAY_HEADLESS_DELIVERY_ENDPOINT = `${LIFERAY_HOST_BASE_URL}/${LIFERAY_HEADLESS_DELIVERY_BASE_PATH}`;
export const LIFERAY_SITE_ID = env.REACT_APP_LIFERAY_SITE_ID;
export const LIFERAY_CONTENT_SET_PROVIDER_KEY = env.REACT_APP_LIFERAY_CONTENT_SET_PROVIDER_KEY;
export const LIFERAY_CLIENT_ID = env.REACT_APP_LIFERAY_CLIENT_ID;
export const LIFERAY_FILE_ENTRY_VERSION = env.REACT_APP_LIFERAY_FILE_ENTRY_VERSION;
export const IMAGE_PATH = env.REACT_APP_IMAGE_PATH;
export const LIFERAY_OAUTH2_AUTHORIZE_URL = env.REACT_APP_LIFERAY_OAUTH2_AUTHORIZE_URL;
export const LIFERAY_OAUTH2_TOKEN_URL = env.REACT_APP_LIFERAY_OAUTH2_TOKEN_URL;